image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  only:
  - development
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  only:
  - development
  script:
    - echo "COMPANY_APIKEY='$COMPANY_APIKEY'" >> ".env"
    - echo "COMPANY_ID='$COMPANY_ID'" >> ".env"
    - echo "COMPANY_WORLD='$COMPANY_WORLD'" >> ".env"
    - npm test