image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

configure_app:
  stage: build
  script:
    - cp .env-example .env
    - cat .env

testing_testing:
  stage: test
  script: npm test