language: node_js
node_js:
  - 'node'
  - 'lts/*'
  
before_deploy: "npm run build"

jobs:
  include:
    - stage: Test
      script: 
        - npm run test

    - stage: Release
      if: tag IS present AND commit_message =~ /^Version /
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true