language: node_js
node_js:
  - '16'
  
before_deploy: "npm run build"

jobs:
  include:
    - stage: Test
      script: 
        - npm run test
      env:
        - COMPANY_APIKEY=$COMPANY_APIKEY
        - COMPANY_ID=$COMPANY_ID
        - COMPANY_WORLD=$COMPANY_WORLD
        - VIRTUAL_AIRLINE_ID=$VIRTUAL_AIRLINE_ID
        
    - stage: Release
      if: tag IS present AND commit_message =~ /^Version /
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true