import { Runway } from './Runway';
import { AirportLocation } from './AirportLocation';
import { AirportFrequency } from './AirportFrequency';

export interface Airport {
  Id: string,
  ICAO: string,
  HasNoRunways: boolean,
  TimeOffsetInSec: number,
  LocalTimeOpenInHoursSinceMidnight: number,
  LocalTimeCloseInHoursSinceMidnight: number,
  IATA: string,
  Name: string,
  State: string,
  CountryCode: string,
  CountryName: string,
  City: string,
  Latitude: number,
  Longitude: number,
  Elevation: number,
  HasLandRunway: boolean,
  HasWaterRunway: boolean,
  HasHelipad: boolean,
  Size: 1 | 2 | 3 | 4 | 5,
  TransitionAltitude: number,
  LastMETARDate: string,
  LastMETARRaw: string,
  Runways: Runway[],
  AirportLocations: AirportLocation[],
  AirportFrequencies: AirportFrequency[],
  IsNotInVanillaFSX: boolean,
  IsNotInVanillaP3D: boolean,
  IsNotInVanillaXPLANE: boolean,
  IsNotInVanillaFS2020: boolean,
  IsClosed: boolean,
  IsValid: boolean,
  MagVar: number,
  IsAddon: number,
  RandomSeed: number,
  LastRandomSeedGeneration: string,
  IsMilitary: boolean,
  HasLights: boolean,
  AirportSource: number,
  LastVeryShortRequestDate: string,
  LastSmallTripRequestDate: string,
  LastMediumTripRequestDate: string,
  LastShortHaulRequestDate: string,
  LastMediumHaulRequestDate: string,
  LastLongHaulRequestDate: string,
  DisplayName: string,
  UTCTimeOpenInHoursSinceMidnight: number,
  UTCTimeCloseInHoursSinceMidnight: number;
}